name: web_app
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Naoto Higuchi <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  hiit_timer:
    path: ../hiit_timer
    
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    path: ../../../code/flutter_web/packages/flutter_web
  flutter_web_ui:
    path: ../../../code/flutter_web/packages/flutter_web_ui
